#!/usr/bin/env bash

#MISE description="Run pyinfra deploy"
#MISE quiet=true

#USAGE arg "<inventory>" help="Name of inventory" {
#USAGE  choices "home" "nvda" "dns"
#USAGE }
#USAGE flag "-t --task <task>" help="Optionally deploy only task."
#USAGE flag "-l --limit <limit>" help="Limit hosts." default="*"
#USAGE flag "--teardown" help="Teardown deployment"
#USAGE flag "-r --refresh" help="Refresh deployment by cleaning cache."

if [[ -z "${usage_inventory}" ]]; then
    echo "[ERROR] Missing inventory."
    exit 1
fi

if [[ "${usage_teardown}" == "true" ]]; then
    __extra_args="--data teardown=True"
fi

if [[ "${usage_refresh}" == "true" ]]; then
    rm -f .env.inventory
fi

## Handle DNS via separate task.
if [[ "${usage_inventory}" == "dns" ]]; then
    usage_inventory="home"
    usage_limit="mac"
    usage_task="cloudflare"
    __extra_args="${__extra_args} --data apply_dns=True"
fi

if [[ -n "${usage_task}" ]]; then
    deploy_file="tasks/${usage_task}.py"
else
    __extra_args="${__extra_args} --data inventory_id=${usage_inventory}"
    deploy_file="deploy.py"
fi

pyinfra -y \
    --limit "${usage_limit}" ${__extra_args} \
	inventories/${usage_inventory}.py \
	${deploy_file}
