#!/usr/bin/env bash

#MISE description="Run pyinfra deploy"
#MISE quiet=true
#MISE dir="pyinfra"

#USAGE arg "<inventory>" help="Name of inventory" {
#USAGE  choices "home" "nvda" "dns"
#USAGE }
#USAGE flag "-r --refresh" help="Refresh deployment by cleaning cache."
#USAGE flag "-t --task <task>" help="Optionally deploy only task."
#USAGE flag "-l --limit <limit>" help="Limit hosts." default="*"
#USAGE flag "--teardown" help="Teardown deployment"
#USAGE arg "[passthru]" var=#true double_dash="required" help="Use -- to start passthrough arguments to pyinfra."

if [[ -f .env ]]; then
    set -a
    # shellcheck disable=SC1091
    source .env
    set +a
fi

if [[ -z "${usage_inventory}" ]]; then
    echo "[ERROR] Missing inventory."
    exit 1
fi

# shellcheck disable=SC2154
if [[ "${usage_refresh}" == "true" ]]; then
    rm -rf ".pyinfra_cache/inventories/${usage_inventory}"
fi

pyinfra_cmd=(pyinfra -y)

# shellcheck disable=SC2154
if [[ "${usage_teardown}" == "true" ]]; then
    pyinfra_cmd+=(--data teardown=True)
fi

## Handle DNS via separate task.
if [[ "${usage_inventory}" == "dns" ]]; then
    usage_inventory="home"
    usage_limit="mac"
    usage_task="cloudflare"
    pyinfra_cmd+=(--data apply_dns=True)
fi

if [[ -n "${usage_task}" ]]; then
    pyinfra_cmd+=(--data apply_tasks="${usage_task}")
fi

pyinfra_cmd+=(
    --limit "${usage_limit}"
    "inventories/${usage_inventory}.py"
    deploy.py
)

if [[ -n "${usage_passthru}" ]]; then
    eval "usage_passthru=(${usage_passthru})"
    pyinfra_cmd+=("${usage_passthru[@]}")
fi

echo "${pyinfra_cmd[@]}"
"${pyinfra_cmd[@]}"
