#!/usr/bin/env bash

#MISE description="Generate pyinfra deploy"
#MISE quiet=true

#USAGE arg "<inventory>" help="Name of inventory" {
#USAGE  choices "home" "nvda"
#USAGE }
#USAGE flag "-t --type <type>" help="Type of key to create." default="ed25519"
#USAGE flag "-A --auth-host <auth_host>" help="Target host to copy the key."

if [[ -z "${usage_inventory}" ]]; then
    echo "[ERROR] Missing inventory."
    exit 1
fi

output_dir=tasks/ssh/files/${usage_inventory}
if ssh-keygen -t ${usage_type} -f "${output_dir}/id_${usage_type}" -C "$(whoami)"; then
    if [[ -n "${usage_auth_host}" ]]; then
        ssh-copy-id -i "${output_dir}/id_${usage_type}" ${usage_auth_host}
    fi
fi
