#!/usr/bin/env bash

#MISE description="Install dependencies using uv"
#MISE quiet=true

#USAGE flag "-d --directory <directory>" help="Path to virtual environment." default=".venv"
#USAGE flag "-U --upgrade" help="Upgrade dependencies."
#USAGE flag "-f --force" help="Force recreate environment."

if [[ -n "${usage_force}" ]]; then
    rm -rf .venv
    if [[ -n "${usage_directory}" ]]; then
        rm -rf "${usage_directory}"
    fi
fi

## Handle a directory different than .venv.
if [[ -n "${usage_directory}" ]]; then
    mkdir -p "${usage_directory}"
    mkdir -p .venv

    real_target="$(realpath .venv)"
    expected_target="$(realpath "${usage_directory}")"

    if [[ "${real_target}" != "${expected_target}" ]]; then
        rm -rf .venv
        ln -nsf "${expected_target}" "${real_target}"
    fi
fi

uv_cmd=(uv sync --all-extras)
if [[ -n "${usage_upgrade}" ]]; then
    uv_cmd+=(--upgrade)
fi

"${uv_cmd[@]}"
