#!/usr/bin/env bash

#MISE description="Install dependencies using uv"
#MISE quiet=true

#USAGE flag "-U --upgrade" help="Upgrade dependencies."

if [[ "${usage_upgrade}" == "true" ]]; then
    __extra_args="--upgrade"
fi

uv sync --extra dev ${__extra_args}
