[env]
_.python.venv = { path = ".venv" }

[tools]
bitwarden-secrets-manager = { version = "latest", version_prefix = "bws-v" }
hadolint = { version = "latest" }
jq = { version = "latest" }
prek = { version = "latest" }
uv = { version = "latest" }
