name: Pyinfra
on:
  push:
    branches:
      - '*'
  pull_request:
jobs:
  dry-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          fetch-depth: 0
      - name: Setup mise
        uses: jdx/mise-action@v4
        with:
          cache: true
      - name: Setup uv
        uses: astral-sh/setup-uv@v10.0.1
        with:
          save-cache: true
      - name: Install
        shell: bash
        run: uv sync --locked
      - name: Test pyinfra
        shell: bash
        run: mise deploy test -- --dry --debug-operations
      - name: Discord Notify
        uses: sarisia/actions-status-discord@v1
        if: always()
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          username: ${{ github.repository }}
